### ISSUE TITLE
feat: Override startup script

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gce-atlantis#41]
Consider overriding the startup script path

https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/8bf8716cd15ed55ffcf7063684a80dd7953eb354/main.tf#L21-L25

And consider overriding the entire `metadata_startup_script` input to avoid the `templatefile` (if there are benefits to it, idk)

**Comment by bschaatsbergen** [comment]
This would likely only result in a broken deployment as we mount a GCE Persisten Disk to the instance. We require to perform a chown on the Atlantis UUID in order to allow Atlantis to write to that mount path.

I would prefer to not add this functionality

**Comment by nitrocode** [comment]
What if someone wanted to add additional items in the bootstrap? Perhaps installing datadog agent or something?

Maybe instead of overriding the script, you could expose a new unit to run a post run or pre run script.

Example https://github.com/search?q=repo%3Aphilips-labs%2Fterraform-aws-github-runner%20post_install&type=code

**Comment by bschaatsbergen** [comment]
What are your thoughts on this @kvanzuijlen ?

**Comment by kvanzuijlen** [comment]
I think for the startup script should be overwritable/extendable. Not sure which of the two it should be though.

We could make the script extendable like this:
```terraform
  metadata_startup_script = <<EOT
    ${var.pre_startup_script}
    ${templatefile(
      "${path.module}/startup-script.sh",
      {
        disk_name     = "atlantis-disk-0",
        atlantis_port = local.atlantis_port,
      }
    )}
    ${var.post_startup_script}
  EOT
```
This gives the end-user the option to add their own script without overriding the default script.

The other option would be to make the script overwritable, which would look a lot cleaner and give the end-user more control over what's in the script. This would however make it easier for them to break stuff and miss out on updates on the default script.

With both of these options, I think the end-user should be advised to make their changes on Docker Image level and only use this if absolutely necessary since it also might impact startup time.

A combination of above suggested solutions would give the end-user the most flexibility but would also make it the most complex to implement/to comprehend. Whatever solution we pick, it should be thoroughly documented.

**Comment by bschaatsbergen** [comment]
As suggested in #69, I think it's a nicer approach to move our existing functionality to cloudinit (see issue) and allow a user to bring its own startup script if necessary.
